### ISSUE TITLE
Clion 2023.1 non-project files protection window bugged

### ISSUE THREAD

**Issue by codethinki** [LiLittleCat/intellij-chatgpt#24]
The Selector is bugged. After hovering over it it displays text and wrong colors below that. It also appears that this happens every time i drag my mouse over the buttons again.

Also this is just an assumption but i think it is displaying the window name "Clion non-project files protection" after hovering over it.

<img width="407" alt="Screenshot 2023-03-31 091925" src="https://user-images.githubusercontent.com/89145039/229051103-21072262-6cac-4c59-a6df-a0784f31f993.png">

**Comment by LiLittleCat** [comment]
Hello @codethinki, is this issue being caused by the plugin? To verify, you may remove the plugin and restart the IDE to see if the problem persists. I am not familiar with the `non-project files protection` feature, so I would like to confirm if the plugin is indeed the culprit.

Based on my understanding, this plugin does not cause any other pop-up issues apart from adding a tool window.

**Comment by codethinki** [comment]
no sorry confused tabs in browser nevermind
