### ISSUE TITLE
Not support Android studio dolphin

### ISSUE THREAD

**Issue by kirin521** [LiLittleCat/intellij-chatgpt#3]

**Comment by LiLittleCat** [comment]
First of all, thank you for using my plugin. 
Try this version to see if it supports: https://drive.google.com/file/d/11SVjO4yJyH7Ridc3Z0Ugs_1VBREwDxW9/view?usp=sharing

**Comment by LiLittleCat** [comment]
> First of all, thank you for using my plugin. Try this version to see if it supports: https://drive.google.com/file/d/11SVjO4yJyH7Ridc3Z0Ugs_1VBREwDxW9/view?usp=sharing

The version I provided earlier cannot work in Android Studio Dolphin either.
I thought at first that it was because the `since-buid` number was too high, but it's not only that.
This plugin uses JCEF(Java Chromium Embedded Framework) to render the content.
In  Android Studio Dolphin, built on IntelliJ Platform 2021.3.1, the JCEF environment is not integrated with the runtime environment by default. So when the plugin starts, the check for support step will fail.

To solve this issue, I suggest you do the following: 

- Check the Registry to make sure jcef is enabled
  - Use 'Search everywhere' (default shortcuts: Double ⇧ Shift) and search `Registry`
[![z7ibx1.png](https://s1.ax1x.com/2022/12/16/z7ibx1.png)](https://imgse.com/i/z7ibx1)
  - make sure the `ide.browser.jcef.enabled` is checked
[![z7iXqK.md.png](https://s1.ax1x.com/2022/12/16/z7iXqK.md.png)](https://imgse.com/i/z7iXqK)
- Change the runtime
  - open menu **Help** > **Find Action…** (default shortcuts: ⇧ Shift + ⌘ Cmd + A) and search for “Choose Boot Java Runtime for the IDE…” and execute
[![z7iH2R.png](https://s1.ax1x.com/2022/12/16/z7iH2R.png)](https://imgse.com/i/z7iH2R)
[![z7FeIg.png](https://s1.ax1x.com/2022/12/16/z7FeIg.png)](https://imgse.com/i/z7FeIg)
  - In the dialog open the drop-down **Select runtime**
[![z7iOr6.png](https://s1.ax1x.com/2022/12/16/z7iOr6.png)](https://imgse.com/i/z7iOr6)
  - Take the default selection or choose from the **More Runtimes** one with JCEF in its title. Confirm with OK.
[![z7iLKx.png](https://s1.ax1x.com/2022/12/16/z7iLKx.png)](https://imgse.com/i/z7iLKx)
  - After downloading and installing you have to apply the changes with **Restart now**
[![z7ivVO.png](https://s1.ax1x.com/2022/12/16/z7ivVO.png)](https://imgse.com/i/z7ivVO)
  - Now you can enjoy the plugin
  - If you failed to set runtime by automatically downloading, you can manually download the runtime in https://github.com/JetBrains/JetBrainsRuntime/releases, search the name in **Select runtime** refered above and download it to the local path, unzip it and choose the **Add Custom Runtime** to use it
[![z7ixaD.png](https://s1.ax1x.com/2022/12/16/z7ixaD.png)](https://imgse.com/i/z7ixaD)
[![z7FpPH.png](https://s1.ax1x.com/2022/12/16/z7FpPH.png)](https://imgse.com/i/z7FpPH)
[![z7izIe.png](https://s1.ax1x.com/2022/12/16/z7izIe.png)](https://imgse.com/i/z7izIe)
  - Use the **Use Default Runtime** button to reset the runtime
[![z7F9Gd.png](https://s1.ax1x.com/2022/12/16/z7F9Gd.png)](https://imgse.com/i/z7F9Gd)

**Comment by kirin521** [comment]
Sorry I just got the message. I'll try later. thanks!

**Comment by obiscr** [comment]
@LiLittleCat 太棒了，解决方案

**Comment by NinhDucAnh** [comment]
I tried so many times your way but it still doesn't work
